from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)


def generate_pdf_report(
    final_score,
    similarity_score,
    skill_match_score,
    matched_skills,
    missing_skills,
    bonus_skills,
    strong_skills,
    limited_skills,
    llm_response
):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title = styles["Title"]
    heading = styles["Heading2"]
    normal = styles["BodyText"]

    story = []

    # ----------------------------------------
    # Title
    # ----------------------------------------

    story.append(
        Paragraph(
            "Resume Screening AI Report",
            title
        )
    )

    story.append(
        Paragraph(
            "AI Powered Resume Analysis",
            normal
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    # ----------------------------------------
    # Scores
    # ----------------------------------------

    story.append(Paragraph("Overall Analysis", heading))

    story.append(
        Paragraph(
            f"<b>ATS Score:</b> {final_score:.2f}%",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Semantic Similarity:</b> {similarity_score}%",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Skill Match Score:</b> {skill_match_score}%",
            normal
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    # ----------------------------------------
    # Skills
    # ----------------------------------------

    story.append(Paragraph("Matched Skills", heading))

    for skill in matched_skills:
        story.append(Paragraph(f"✓ {skill}", normal))

    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("Missing Skills", heading))

    for skill in missing_skills:
        story.append(Paragraph(f"✗ {skill}", normal))

    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("Bonus Skills", heading))

    for skill in bonus_skills:
        story.append(Paragraph(f"★ {skill}", normal))

    story.append(Spacer(1, 0.25 * inch))

    # ----------------------------------------
    # Evidence
    # ----------------------------------------

    story.append(Paragraph("Strong Evidence Skills", heading))

    for skill in strong_skills:
        story.append(Paragraph(f"✓ {skill}", normal))

    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("Limited Evidence Skills", heading))

    for skill in limited_skills:
        story.append(Paragraph(f"⚠ {skill}", normal))

    story.append(Spacer(1, 0.25 * inch))

    # ----------------------------------------
    # AI Career Advisor
    # ----------------------------------------

    story.append(Paragraph("AI Career Advisor", heading))

    story.append(Paragraph("<b>Strengths</b>", normal))

    for item in llm_response["strengths"]:
        story.append(Paragraph(f"• {item}", normal))

    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("<b>Improvement Areas</b>", normal))

    for item in llm_response["improvement_areas"]:
        story.append(Paragraph(f"• {item}", normal))

    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("<b>Learning Roadmap</b>", normal))

    for item in llm_response["learning_roadmap"]:
        story.append(Paragraph(f"• {item}", normal))

    story.append(Spacer(1, 0.15 * inch))

    interview = llm_response["interview_readiness"]

    story.append(Paragraph("<b>Interview Readiness</b>", normal))

    story.append(
        Paragraph(
            f"<b>Score:</b> {interview['score']}%",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Level:</b> {interview['level']}",
            normal
        )
    )

    story.append(
        Paragraph(
            interview["reason"],
            normal
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    # ----------------------------------------
    # Footer
    # ----------------------------------------

    story.append(
        Paragraph(
            "<font color='grey'>Generated by Resume Screening AI</font>",
            normal
        )
    )

    doc.build(story)

    buffer.seek(0)

    return buffer